# Generated by Django 3.1.6 on 2021-02-25 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('vehicle_manufacture_year', models.DateField()),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('date_and_time_of_accident', models.DateTimeField()),
                ('accident_location', models.CharField(max_length=255)),
                ('type_of_loss', models.CharField(max_length=100)),
                ('description_of_loss', models.TextField(max_length=300)),
                ('police_report_lodged', models.BooleanField()),
                ('people_injured', models.BooleanField()),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('document_in_pdf_format', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
