# Generated by Django 3.1.6 on 2021-02-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_status',
            field=models.BooleanField(default=False),
        ),
    ]
