# Generated by Django 3.1.6 on 2021-02-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_claim_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_status',
            new_name='claim_approved',
        ),
    ]
