# Generated by Django 3.1.6 on 2021-02-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_auto_20210225_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='type_of_loss',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='claim',
            name='vehicle_manufacture_year',
            field=models.CharField(max_length=4),
        ),
    ]
