# Generated by Django 3.1.6 on 2021-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_auto_20210226_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='people_injured',
            new_name='anybody_injured',
        ),
        migrations.AlterField(
            model_name='claim',
            name='vehicle_number',
            field=models.CharField(max_length=8),
        ),
    ]
