# Generated by Django 3.1.6 on 2021-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_auto_20210226_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='type_of_loss',
            field=models.CharField(max_length=20),
        ),
    ]
