# Generated by Django 3.1.6 on 2021-02-26 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_auto_20210226_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='document_in_pdf_format',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
